/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false worker/worker-configuration.d.ts` (hash: 939ac98d66bcadfd2d9fa17b1a6606d5)
interface __BaseEnv_Env {
  DB: D1Database;
  APP_BASE_URL: 'https://promptdesk-worker.openedutools.workers.dev';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'APP_BASE_URL'>> {}
}
